import { docs } from "fumadocs-mdx:collections/server";
import { loader } from "fumadocs-core/source";
import { createElement } from "react";
import {
  FaArrowPointer,
  FaArrowRightArrowLeft,
  FaBarsStaggered,
  FaBell,
  FaBoxArchive,
  FaBug,
  FaBullhorn,
  FaCalculator,
  FaCamera,
  FaChartColumn,
  FaCircleExclamation,
  FaCircleInfo,
  FaArrowRightFromBracket,
  FaClipboardList,
  FaClock,
  FaCode,
  FaComments,
  FaCube,
  FaEnvelope,
  FaEyeSlash,
  FaFaceSmile,
  FaFileCode,
  FaFilter,
  FaFire,
  FaGavel,
  FaGear,
  FaGift,
  FaGifts,
  FaGraduationCap,
  FaHand,
  FaHandPointer,
  FaHeart,
  FaHouse,
  FaIdCard,
  FaImage,
  FaKey,
  FaLayerGroup,
  FaLightbulb,
  FaLink,
  FaLock,
  FaMicrophone,
  FaMoneyBill,
  FaPaintbrush,
  FaRotate,
  FaScaleBalanced,
  FaShieldHalved,
  FaSliders,
  FaStar,
  FaTable,
  FaTag,
  FaTerminal,
  FaTicket,
  FaThumbsUp,
  FaUserGroup,
  FaUserMinus,
  FaUserPlus,
  FaUsers,
  FaVolumeHigh
} from "react-icons/fa6";

const pageIcons = {
  "academic-cap": FaGraduationCap,
  "adjustments-horizontal": FaSliders,
  "archive-box-arrow-down": FaBoxArchive,
  "arrow-path-rounded-square": FaRotate,
  "arrow-right-from-bracket": FaArrowRightFromBracket,
  "arrows-right-left": FaArrowRightArrowLeft,
  "circle-exclamation": FaCircleExclamation,
  banknotes: FaMoneyBill,
  "bell-alert": FaBell,
  "bug-ant": FaBug,
  calculator: FaCalculator,
  camera: FaCamera,
  "chart-bar-square": FaChartColumn,
  "chat-bubble-bottom-center-text": FaComments,
  "clipboard-document-list": FaClipboardList,
  clock: FaClock,
  "cog-6-tooth": FaGear,
  "code-bracket": FaCode,
  "code-bracket-square": FaFileCode,
  "command-line": FaTerminal,
  "cube-transparent": FaCube,
  "cursor-arrow-rays": FaArrowPointer,
  "cursor-arrow-ripple": FaHandPointer,
  envelope: FaEnvelope,
  "eye-slash": FaEyeSlash,
  "face-smile": FaFaceSmile,
  fire: FaFire,
  funnel: FaFilter,
  gavel: FaGavel,
  gift: FaGift,
  "gift-top": FaGifts,
  "hand-raised": FaHand,
  "hand-thumb-up": FaThumbsUp,
  heart: FaHeart,
  home: FaHouse,
  identification: FaIdCard,
  "information-circle": FaCircleInfo,
  key: FaKey,
  "light-bulb": FaLightbulb,
  link: FaLink,
  "lock-closed": FaLock,
  megaphone: FaBullhorn,
  microphone: FaMicrophone,
  "paint-brush": FaPaintbrush,
  photo: FaImage,
  "queue-list": FaBarsStaggered,
  "rectangle-stack": FaLayerGroup,
  scale: FaScaleBalanced,
  "shield-exclamation": FaShieldHalved,
  "speaker-wave": FaVolumeHigh,
  star: FaStar,
  tag: FaTag,
  ticket: FaTicket,
  "user-minus": FaUserMinus,
  "user-plus": FaUserPlus,
  "user-group": FaUserGroup,
  users: FaUsers,
  variable: FaTable
};

export const source = loader({
  baseUrl: "/",
  icon(icon) {
    if (!icon) {
      return null;
    }

    const Icon = pageIcons[icon];

    return Icon ? createElement(Icon, { className: "size-4" }) : null;
  },
  source: docs.toFumadocsSource()
});
